### ISSUE TITLE
Croupierra dagoenean ez da botea banatzen

### ISSUE THREAD

**Issue by Xabiier** [Thadah/BlackJack#41]

**Comment by Thadah** [comment]
Bug-a dirua "Ranking" listako jokalari artifizialei pasatzen zitzaielako gertatzen zen.
Iteradorea ListaJokalariei pasatzen konpontzen da bug hau, baina beste bug bat sortzen da.
Orain Jokalari guztiek irabazten dute "bakoitzari" int balioa.
Bug-a konpontzeko, nolabait Ranking listan dauden Jokalariak bakarrik kontuan hartu behar ditugu, ListaJokalariak iteradorea boteaBanatu() metodoan aldatu gabe.

CHALLENGE ACCEPTED.
